### ISSUE TITLE
Cannot delete task dependencies

### ISSUE THREAD

**Issue by mkuo005** [uniba-swt/LetSynchronise#174]
Unable to delete task dependencies in "Define Task Dependencies" section.
Example system: [system.json](https://github.com/uniba-swt/LetSynchronise/files/14106641/system.json)

**Comment by eyip002** [comment]
Caused by dependency having the same name as a port

**Comment by eyip002** [comment]
Also bad style to reuse the same name for different modelling elements.

**Comment by eyip002** [comment]
7957a78
