### ISSUE TITLE
Heterogenous core support not visualised correctly

### ISSUE THREAD

**Issue by mkuo005** [uniba-swt/LetSynchronise#175]
The instance is allocated to core 2 with a speed up of 2.
![image](https://github.com/uniba-swt/LetSynchronise/assets/13615523/96fdffd6-c4b2-48c2-ba6e-24cb83043cc4)

**Comment by eyip002** [comment]
Can you give more information to replicate the issue?

**Comment by eyip002** [comment]
External scheduler generating invalid schedules?

**Comment by mkuo005** [comment]
the external schedule taking into account the 2x speed up so the schedule appears to be invaild but should be vaild since that core executes 2x speed up.

**Comment by eyip002** [comment]
External multi-core scheduler not reporting correct execution times
